/** @type {import("tailwindcss").Config} */
module.exports = {
    content: [
        "./app/**/*.{js,ts,jsx,tsx,mdx}",
        "./components/**/*.{js,ts,jsx,tsx,mdx}",
    ],
    theme: {
        extend: {
            colors: {
                "surface": "#fbf9fb",
                "surface-container": "#efedef",
                "surface-container-low": "#f5f3f5",
                "surface-container-high": "#eae7ea",
                "surface-container-highest": "#e4e2e4",
                "surface-variant": "#e4e2e4",
                "surface-dim": "#dbd9db",
                "surface-bright": "#fbf9fb",
                "on-surface": "#1b1b1d",
                "on-surface-variant": "#44474d",
                "on-background": "#1b1b1d",
                "background": "#fbf9fb",
                "primary": "#000000",
                "on-primary": "#ffffff",
                "primary-container": "#0d1c32",
                "on-primary-container": "#76849f",
                "secondary": "#5d5f5f",
                "on-secondary": "#ffffff",
                "secondary-container": "#dfe0e0",
                "on-secondary-container": "#616363",
                "tertiary": "#000000",
                "on-tertiary": "#ffffff",
                "tertiary-container": "#2b1701",
                "on-tertiary-container": "#9f7d5b",
                "outline": "#75777e",
                "outline-variant": "#c5c6cd",
                "error": "#ba1a1a",
                "on-error": "#ffffff",
                "error-container": "#ffdad6",
                "on-error-container": "#93000a",
                "inverse-surface": "#303032",
                "inverse-on-surface": "#f2f0f2",
                "inverse-primary": "#b9c7e4",
                "primary-fixed": "#d6e3ff",
                "primary-fixed-dim": "#b9c7e4",
                "orange": "#f97316",
                "navy": "#0d1c32",
            },
            spacing: {
                "xs": "8px",
                "sm": "16px",
                "md": "24px",
                "lg": "40px",
                "xl": "64px",
                "gutter": "24px",
                "margin-mobile": "16px",
                "base": "4px",
            },
            borderRadius: {
                DEFAULT: "0.25rem",
                lg: "0.5rem",
                xl: "0.75rem",
                full: "9999px",
            },
            fontFamily: {
                "body-md": ["Inter"],
                "headline-md": ["Inter"],
                "headline-lg": ["Inter"],
                "headline-lg-mobile": ["Inter"],
                "display-lg": ["Inter"],
                "label-md": ["Inter"],
                "label-sm": ["Inter"],
                "body-sm": ["Inter"],
                "body-lg": ["Inter"],
            },
            fontSize: {
                "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
                "headline-md": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
                "headline-lg": ["32px", { lineHeight: "1.3", fontWeight: "700" }],
                "headline-lg-mobile": ["24px", { lineHeight: "1.3", fontWeight: "700" }],
                "display-lg": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
                "label-md": ["14px", { lineHeight: "1", letterSpacing: "0.01em", fontWeight: "600" }],
                "label-sm": ["12px", { lineHeight: "1", fontWeight: "500" }],
                "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
                "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
            },
            maxWidth: {
                "container-max": "1280px",
            },
            boxShadow: {
                "level-1": "0px 2px 4px rgba(0, 0, 0, 0.05)",
                "level-2": "0px 10px 20px rgba(0, 0, 0, 0.08)",
            },
        },
    },
    plugins: [],
};